<?php

return [
    '' => 'site/index',
    'about-coral-perfumes' => 'site/about',
    'coral-perfumes-private-label' => 'site/private-label',
    'coral-perfumes-showrooms' => 'site/showrooms',
    'coral-perfumes-contact' => 'site/contact',
    'forgot-password' => 'site/forgot',
    'login-signup' => 'site/login-signup',
    'terms-condition' => 'site/terms-condition',
    'privacy-policy' => 'site/privacy-policy',
    'return-policy' => 'site/return-policy',
    'contact' => 'site/contact',
    'faq' => 'site/faq',
    'product_detail/<product:\w+(-\w+)*>' => 'product/product_detail',
    'my-account' => 'myaccounts/user/index',
    'my-orders' => 'myaccounts/user/my-orders',
    'my-reviews' => 'myaccounts/user/my-reviews',
    'wish-list' => 'myaccounts/user/wish-list',
    'personal-info' => 'myaccounts/user/personal-info',
    'contact-info' => 'myaccounts/user/update-contact-info',
    'coral-perfumes-blog-detail/<id>' => 'site/blog-detail',
    'coral-perfumes-blogs' => 'site/our-blog',
];
